### ISSUE TITLE
Flux Gym Windows 11 AMD GPU 7900 XTX  "RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`"

### ISSUE THREAD

**Issue by HarmlessDiva** [CS1o/Stable-Diffusion-Info#44]
Hello Guys im new to this Lora Training thing.

My setup is windows 11 AMD 7900 XTX

I precisly installed flux gym with the following guide "https://github.com/CS1o/Stable-Diffusion-Info/wiki/Lora-Trainer-Setup-Guides#amd-install-guides"

Installation was fine until i got the following error message:
"""
ee its traceback):
module 'torch.library' has no attribute 'custom_op'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Slut Gym\fluxgym\app.py", line 19, in <module>
    from library import flux_train_utils, huggingface_util
  File "F:\Slut Gym\fluxgym\sd-scripts\library\flux_train_utils.py", line 17, in <module>
    from library import flux_models, flux_utils, strategy_base, train_util
  File "F:\Slut Gym\fluxgym\sd-scripts\library\train_util.py", line 48, in <module>
    from diffusers import (
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 934, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 934, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 933, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 945, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
module 'torch.library' has no attribute 'custom_op'
"""

Then i fixed this issue by doing this i dunno if this was the correct way, at least flux gym webui started then after this:

"""
Upgrade PyTorch to ≥ 2.2 with cu118 ABI
-.\venv\Scripts\Activate.ps1
 
Uninstall old torch
pip uninstall -y torch torchvision torchaudio
 
Reinstall torch≥2.2+cu118
pip install torch==2.7.1+cu118 torchvision==0.22.1+cu118 torchaudio==2.7.1+cu118  --index-url https://download.pytorch.org/whl/cu118
 
Re install other deps (flash attn/sage/xformers etc):
pip install diffusers accelerate transformers peft safetensors einops bitsandbytes xformers flash-attn sage-attention
 
Relaunch
 .\Start-FluxGym-Zluda.bat
"""

Then i started the lora training and got the follow main error:
"RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmEx(..., CUDA_R_16BF, ..., CUBLAS_GEMM_DEFAULT_TENSOR_OP)`"

Here is the full error log:

"""
[2025-07-22 19:54:10] [INFO] Running F:\Slut Gym\fluxgym\outputs\fifthtry\train.bat
[2025-07-22 19:54:10] [INFO] 
[2025-07-22 19:54:10] [INFO] (venv) F:\Slut Gym\fluxgym>accelerate launch   --mixed_precision bf16   --num_cpu_threads_per_process 1   sd-scripts/flux_train_network.py   --pretrained_model_name_or_path "F:\Slut Gym\fluxgym\models\unet\flux1-dev.sft"   --clip_l "F:\Slut Gym\fluxgym\models\clip\clip_l.safetensors"   --t5xxl "F:\Slut Gym\fluxgym\models\clip\t5xxl_fp16.safetensors"   --ae "F:\Slut Gym\fluxgym\models\vae\ae.sft"   --cache_latents_to_disk   --save_model_as safetensors   --sdpa --persistent_data_loader_workers   --max_data_loader_n_workers 2   --seed 42   --gradient_checkpointing   --mixed_precision bf16   --save_precision bf16   --network_module networks.lora_flux   --network_dim 4   --optimizer_type adamw8bit   --learning_rate 8e-4   --cache_text_encoder_outputs   --cache_text_encoder_outputs_to_disk   --fp8_base   --highvram   --max_train_epochs 8   --save_every_n_epochs 4   --dataset_config "F:\Slut Gym\fluxgym\outputs\fifthtry\dataset.toml"   --output_dir "F:\Slut Gym\fluxgym\outputs\fifthtry"   --output_name fifthtry   --timestep_sampling shift   --discrete_flow_shift 3.1582   --model_prediction_type raw   --guidance_scale 1   --loss_type l2   --fp8_base_unet   --full_fp16   --no_half_vae
[2025-07-22 19:54:15] [INFO] The following values were not passed to `accelerate launch` and had defaults used instead:
[2025-07-22 19:54:15] [INFO] `--num_processes` was set to a value of `1`
[2025-07-22 19:54:15] [INFO] `--num_machines` was set to a value of `1`
[2025-07-22 19:54:15] [INFO] `--dynamo_backend` was set to a value of `'no'`
[2025-07-22 19:54:15] [INFO] To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2025-07-22 19:54:20] [INFO] `flash-attn` is not available or the version is too old. Please install `flash-attn>=2.6.3`.
[2025-07-22 19:54:20] [INFO] `sageattention` is not available or the version is too old. Please install `sageattention>=2.1.1`.
[2025-07-22 19:54:20] [INFO] `xformers` is not available or the version is too old. Please install `xformers>=0.0.29`.
[2025-07-22 19:54:21] [INFO] 2025-07-22 19:54:21 INFO     highvram is enabled /           train_util.py:4318
[2025-07-22 19:54:21] [INFO] highvramが有効です
[2025-07-22 19:54:21] [INFO] WARNING  cache_latents_to_disk is        train_util.py:4335
[2025-07-22 19:54:21] [INFO] enabled, so cache_latents is
[2025-07-22 19:54:21] [INFO] also enabled /
[2025-07-22 19:54:21] [INFO] cache_latents_to_diskが有効なた
[2025-07-22 19:54:21] [INFO] め、cache_latentsを有効にします
[2025-07-22 19:54:21] [INFO] 2025-07-22 19:54:21 INFO     Checking the state dict:          flux_utils.py:43
[2025-07-22 19:54:21] [INFO] Diffusers or BFL, dev or schnell
[2025-07-22 19:54:21] [INFO] INFO     t5xxl_max_token_length:  flux_train_network.py:164
[2025-07-22 19:54:21] [INFO] 512
[2025-07-22 19:54:21] [INFO] F:\Slut Gym\fluxgym\venv\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
[2025-07-22 19:54:21] [INFO] warnings.warn(
[2025-07-22 19:54:21] [INFO] You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
[2025-07-22 19:54:21] [INFO] INFO     Loading dataset config from   train_network.py:507
[2025-07-22 19:54:21] [INFO] F:\Slut
[2025-07-22 19:54:21] [INFO] Gym\fluxgym\outputs\fifthtry\
[2025-07-22 19:54:21] [INFO] dataset.toml
[2025-07-22 19:54:21] [INFO] INFO     prepare images.                 train_util.py:2072
[2025-07-22 19:54:21] [INFO] INFO     get image size from name of     train_util.py:1965
[2025-07-22 19:54:21] [INFO] cache files
[2025-07-22 19:54:21] [INFO] 0%|          | 0/21 [00:00<?, ?it/s]
100%|██████████| 21/21 [00:00<?, ?it/s]
[2025-07-22 19:54:21] [INFO] INFO     set image size from cache       train_util.py:1995
[2025-07-22 19:54:21] [INFO] files: 0/21
[2025-07-22 19:54:21] [INFO] INFO     found directory F:\Slut         train_util.py:2019
[2025-07-22 19:54:21] [INFO] Gym\fluxgym\datasets\fifthtry
[2025-07-22 19:54:21] [INFO] contains 21 image files
[2025-07-22 19:54:21] [INFO] read caption:   0%|          | 0/21 [00:00<?, ?it/s]
read caption: 100%|██████████| 21/21 [00:00<?, ?it/s]
[2025-07-22 19:54:21] [INFO] INFO     210 train images with repeats.  train_util.py:2116
[2025-07-22 19:54:21] [INFO] INFO     0 reg images with repeats.      train_util.py:2120
[2025-07-22 19:54:21] [INFO] WARNING  no regularization images /      train_util.py:2125
[2025-07-22 19:54:21] [INFO] 正則化画像が見つかりませんでし
[2025-07-22 19:54:21] [INFO] た
[2025-07-22 19:54:21] [INFO] INFO     [Dataset 0]                     config_util.py:580
[2025-07-22 19:54:21] [INFO] batch_size: 1
[2025-07-22 19:54:21] [INFO] resolution: (512, 512)
[2025-07-22 19:54:21] [INFO] resize_interpolation: None
[2025-07-22 19:54:21] [INFO] enable_bucket: False
[2025-07-22 19:54:21] [INFO] 
[2025-07-22 19:54:21] [INFO] [Subset 0 of Dataset 0]
[2025-07-22 19:54:21] [INFO] image_dir: "F:\Slut
[2025-07-22 19:54:21] [INFO] Gym\fluxgym\datasets\fifthtry"
[2025-07-22 19:54:21] [INFO] image_count: 21
[2025-07-22 19:54:21] [INFO] num_repeats: 10
[2025-07-22 19:54:21] [INFO] shuffle_caption: False
[2025-07-22 19:54:21] [INFO] keep_tokens: 1
[2025-07-22 19:54:21] [INFO] caption_dropout_rate: 0.0
[2025-07-22 19:54:21] [INFO] caption_dropout_every_n_epo
[2025-07-22 19:54:21] [INFO] chs: 0
[2025-07-22 19:54:21] [INFO] caption_tag_dropout_rate:
[2025-07-22 19:54:21] [INFO] 0.0
[2025-07-22 19:54:21] [INFO] caption_prefix: None
[2025-07-22 19:54:21] [INFO] caption_suffix: None
[2025-07-22 19:54:21] [INFO] color_aug: False
[2025-07-22 19:54:21] [INFO] flip_aug: False
[2025-07-22 19:54:21] [INFO] face_crop_aug_range: None
[2025-07-22 19:54:21] [INFO] random_crop: False
[2025-07-22 19:54:21] [INFO] token_warmup_min: 1,
[2025-07-22 19:54:21] [INFO] token_warmup_step: 0,
[2025-07-22 19:54:21] [INFO] alpha_mask: False
[2025-07-22 19:54:21] [INFO] resize_interpolation: None
[2025-07-22 19:54:21] [INFO] custom_attributes: {}
[2025-07-22 19:54:21] [INFO] is_reg: False
[2025-07-22 19:54:21] [INFO] class_tokens: h3ll0
[2025-07-22 19:54:21] [INFO] caption_extension: .txt
[2025-07-22 19:54:21] [INFO] 
[2025-07-22 19:54:21] [INFO] 
[2025-07-22 19:54:21] [INFO] INFO     [Prepare dataset 0]             config_util.py:592
[2025-07-22 19:54:21] [INFO] INFO     loading image sizes.             train_util.py:987
[2025-07-22 19:54:21] [INFO] 0%|          | 0/21 [00:00<?, ?it/s]
100%|██████████| 21/21 [00:00<?, ?it/s]
[2025-07-22 19:54:21] [INFO] INFO     prepare dataset                 train_util.py:1012
[2025-07-22 19:54:21] [INFO] INFO     preparing accelerator         train_network.py:581
[2025-07-22 19:54:21] [INFO] accelerator device: cuda
[2025-07-22 19:54:21] [INFO] INFO     Checking the state dict:          flux_utils.py:43
[2025-07-22 19:54:21] [INFO] Diffusers or BFL, dev or schnell
[2025-07-22 19:54:21] [INFO] INFO     Building Flux model dev from BFL flux_utils.py:101
[2025-07-22 19:54:21] [INFO] checkpoint
[2025-07-22 19:54:21] [INFO] INFO     Loading state dict from F:\Slut  flux_utils.py:118
[2025-07-22 19:54:21] [INFO] Gym\fluxgym\models\unet\flux1-de
[2025-07-22 19:54:21] [INFO] v.sft
[2025-07-22 19:54:22] [INFO] 2025-07-22 19:54:22 INFO     Loaded Flux: <All keys matched   flux_utils.py:137
[2025-07-22 19:54:22] [INFO] successfully>
[2025-07-22 19:54:22] [INFO] INFO     Cast FLUX model to fp8.  flux_train_network.py:115
[2025-07-22 19:54:22] [INFO] This may take a while.
[2025-07-22 19:54:22] [INFO] You can reduce the time
[2025-07-22 19:54:22] [INFO] by using fp8 checkpoint.
[2025-07-22 19:54:22] [INFO] /
[2025-07-22 19:54:22] [INFO] FLUXモデルをfp8に変換し
[2025-07-22 19:54:22] [INFO] ています。これには時間が
[2025-07-22 19:54:22] [INFO] かかる場合があります。fp
[2025-07-22 19:54:22] [INFO] 8チェックポイントを使用
[2025-07-22 19:54:22] [INFO] することで時間を短縮でき
[2025-07-22 19:54:22] [INFO] ます。
[2025-07-22 19:55:39] [INFO] 2025-07-22 19:55:39 INFO     Building CLIP-L                  flux_utils.py:179
[2025-07-22 19:55:39] [INFO] INFO     Loading state dict from F:\Slut  flux_utils.py:275
[2025-07-22 19:55:39] [INFO] Gym\fluxgym\models\clip\clip_l.s
[2025-07-22 19:55:39] [INFO] afetensors
[2025-07-22 19:55:40] [INFO] 2025-07-22 19:55:40 INFO     Loaded CLIP-L: <All keys matched flux_utils.py:278
[2025-07-22 19:55:40] [INFO] successfully>
[2025-07-22 19:55:41] [INFO] 2025-07-22 19:55:41 INFO     Loading state dict from F:\Slut  flux_utils.py:330
[2025-07-22 19:55:41] [INFO] Gym\fluxgym\models\clip\t5xxl_fp
[2025-07-22 19:55:41] [INFO] 16.safetensors
[2025-07-22 19:56:10] [INFO] 2025-07-22 19:56:10 INFO     Loaded T5xxl: <All keys matched  flux_utils.py:333
[2025-07-22 19:56:10] [INFO] successfully>
[2025-07-22 19:56:10] [INFO] INFO     Building AutoEncoder             flux_utils.py:144
[2025-07-22 19:56:11] [INFO] 2025-07-22 19:56:11 INFO     Loading state dict from F:\Slut  flux_utils.py:149
[2025-07-22 19:56:11] [INFO] Gym\fluxgym\models\vae\ae.sft
[2025-07-22 19:56:11] [INFO] INFO     Loaded AE: <All keys matched     flux_utils.py:152
[2025-07-22 19:56:11] [INFO] successfully>
[2025-07-22 19:56:11] [INFO] import network module: networks.lora_flux
[2025-07-22 19:56:13] [INFO] 2025-07-22 19:56:13 INFO     [Dataset 0]                     train_util.py:2613
[2025-07-22 19:56:13] [INFO] INFO     caching latents with caching    train_util.py:1115
[2025-07-22 19:56:13] [INFO] strategy.
[2025-07-22 19:56:13] [INFO] INFO     caching latents...              train_util.py:1164
[2025-07-22 19:56:14] [INFO] 0%|          | 0/21 [00:00<?, ?it/s]
  0%|          | 0/21 [00:00<?, ?it/s]
[2025-07-22 19:56:14] [INFO] Traceback (most recent call last):
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\sd-scripts\flux_train_network.py", line 566, in <module>
[2025-07-22 19:56:14] [INFO] trainer.train(args)
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\sd-scripts\train_network.py", line 623, in train
[2025-07-22 19:56:14] [INFO] train_dataset_group.new_cache_latents(vae, accelerator)
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\sd-scripts\library\train_util.py", line 2614, in new_cache_latents
[2025-07-22 19:56:14] [INFO] dataset.new_cache_latents(model, accelerator)
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\sd-scripts\library\train_util.py", line 1204, in new_cache_latents
[2025-07-22 19:56:14] [INFO] submit_batch(batch, current_condition)
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\sd-scripts\library\train_util.py", line 1150, in submit_batch
[2025-07-22 19:56:14] [INFO] caching_strategy.cache_batch_latents(model, batch, cond.flip_aug, cond.alpha_mask, cond.random_crop)
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\sd-scripts\library\strategy_flux.py", line 228, in cache_batch_latents
[2025-07-22 19:56:14] [INFO] self._default_cache_batch_latents(
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\sd-scripts\library\strategy_base.py", line 510, in _default_cache_batch_latents
[2025-07-22 19:56:14] [INFO] latents_tensors = encode_by_vae(img_tensor).to("cpu")
[2025-07-22 19:56:14] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\sd-scripts\library\strategy_flux.py", line 224, in <lambda>
[2025-07-22 19:56:14] [INFO] encode_by_vae = lambda img_tensor: vae.encode(img_tensor).to("cpu")
[2025-07-22 19:56:14] [INFO] ^^^^^^^^^^^^^^^^^^^^^^
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\sd-scripts\library\flux_models.py", line 349, in encode
[2025-07-22 19:56:14] [INFO] z = self.reg(self.encoder(x))
[2025-07-22 19:56:14] [INFO] ^^^^^^^^^^^^^^^
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
[2025-07-22 19:56:14] [INFO] return self._call_impl(*args, **kwargs)
[2025-07-22 19:56:14] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
[2025-07-22 19:56:14] [INFO] return forward_call(*args, **kwargs)
[2025-07-22 19:56:14] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\sd-scripts\library\flux_models.py", line 199, in forward
[2025-07-22 19:56:14] [INFO] hs = [self.conv_in(x)]
[2025-07-22 19:56:14] [INFO] ^^^^^^^^^^^^^^^
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
[2025-07-22 19:56:14] [INFO] return self._call_impl(*args, **kwargs)
[2025-07-22 19:56:14] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
[2025-07-22 19:56:14] [INFO] return forward_call(*args, **kwargs)
[2025-07-22 19:56:14] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
[2025-07-22 19:56:14] [INFO] return self._conv_forward(input, self.weight, self.bias)
[2025-07-22 19:56:14] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-22 19:56:14] [INFO] File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
[2025-07-22 19:56:14] [INFO] return F.conv2d(
[2025-07-22 19:56:14] [INFO] ^^^^^^^^^
[2025-07-22 19:56:14] [INFO] RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
[2025-07-22 19:56:18] [INFO] Traceback (most recent call last):
[2025-07-22 19:56:18] [INFO] File "<frozen runpy>", line 198, in _run_module_as_main
[2025-07-22 19:56:18] [INFO] File "<frozen runpy>", line 88, in _run_code
[2025-07-22 19:56:18] [INFO] File "F:\Slut Gym\fluxgym\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2025-07-22 19:56:18] [INFO] File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2025-07-22 19:56:18] [INFO] args.func(args)
[2025-07-22 19:56:18] [INFO] File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2025-07-22 19:56:18] [INFO] simple_launcher(args)
[2025-07-22 19:56:18] [INFO] File "F:\Slut Gym\fluxgym\venv\Lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2025-07-22 19:56:18] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2025-07-22 19:56:18] [INFO] subprocess.CalledProcessError: Command '['F:\\Slut Gym\\fluxgym\\venv\\Scripts\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'F:\\Slut Gym\\fluxgym\\models\\unet\\flux1-dev.sft', '--clip_l', 'F:\\Slut Gym\\fluxgym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'F:\\Slut Gym\\fluxgym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'F:\\Slut Gym\\fluxgym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adamw8bit', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '8', '--save_every_n_epochs', '4', '--dataset_config', 'F:\\Slut Gym\\fluxgym\\outputs\\fifthtry\\dataset.toml', '--output_dir', 'F:\\Slut Gym\\fluxgym\\outputs\\fifthtry', '--output_name', 'fifthtry', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2', '--fp8_base_unet', '--full_fp16', '--no_half_vae']' returned non-zero exit status 1.
[2025-07-22 19:56:19] [ERROR] Command exited with code 1
[2025-07-22 19:56:19] [INFO] Runner: <LogsViewRunner nb_logs=182 exit_code=1>
"""

I hope some1 can help me i dont want to train personal loras online in the cloud because the datasets. I dont trust those side online providers due GDPR.

**Comment by CS1o** [comment]
Hey,
after changing the torch version to 2.7.1, did you replaced the three files in the venv\Lib\site-packages\torch folder with the zluda files before relaunching?

**Comment by HarmlessDiva** [comment]
i did it in the first place, like you mention in step 7 of your guide but after doing this step:

where i deinstalled the torch torchvision and torchaudio and installed it again like i mention, i guessed it overwrite the three files in lib. So i overwrite them again with the 3 zluda files and then it seemed to work but then a new error occured :D.

"""
[2025-07-24 00:18:19] [INFO] Traceback (most recent call last):
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\sd-scripts\flux_train_network.py", line 566, in <module>
[2025-07-24 00:18:19] [INFO] trainer.train(args)
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\sd-scripts\train_network.py", line 640, in train
[2025-07-24 00:18:19] [INFO] self.cache_text_encoder_outputs_if_needed(args, accelerator, unet, vae, text_encoders, train_dataset_group, weight_dtype)
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\sd-scripts\flux_train_network.py", line 237, in cache_text_encoder_outputs_if_needed
[2025-07-24 00:18:19] [INFO] dataset.new_cache_text_encoder_outputs(text_encoders, accelerator)
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\sd-scripts\library\train_util.py", line 2636, in new_cache_text_encoder_outputs
[2025-07-24 00:18:19] [INFO] dataset.new_cache_text_encoder_outputs(models, accelerator)
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\sd-scripts\library\train_util.py", line 1343, in new_cache_text_encoder_outputs
[2025-07-24 00:18:19] [INFO] caching_strategy.cache_batch_outputs(tokenize_strategy, models, text_encoding_strategy, batch)
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\sd-scripts\library\strategy_flux.py", line 162, in cache_batch_outputs
[2025-07-24 00:18:19] [INFO] l_pooled, t5_out, txt_ids, _ = flux_text_encoding_strategy.encode_tokens(tokenize_strategy, models, tokens_and_masks)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\sd-scripts\library\strategy_flux.py", line 68, in encode_tokens
[2025-07-24 00:18:19] [INFO] l_pooled = clip_l(l_tokens.to(clip_l.device))["pooler_output"]
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
[2025-07-24 00:18:19] [INFO] return self._call_impl(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
[2025-07-24 00:18:19] [INFO] return forward_call(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 986, in forward
[2025-07-24 00:18:19] [INFO] return self.text_model(
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
[2025-07-24 00:18:19] [INFO] return self._call_impl(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
[2025-07-24 00:18:19] [INFO] return forward_call(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 890, in forward
[2025-07-24 00:18:19] [INFO] encoder_outputs = self.encoder(
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
[2025-07-24 00:18:19] [INFO] return self._call_impl(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
[2025-07-24 00:18:19] [INFO] return forward_call(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 813, in forward
[2025-07-24 00:18:19] [INFO] layer_outputs = encoder_layer(
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
[2025-07-24 00:18:19] [INFO] return self._call_impl(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
[2025-07-24 00:18:19] [INFO] return forward_call(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 548, in forward
[2025-07-24 00:18:19] [INFO] hidden_states, attn_weights = self.self_attn(
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
[2025-07-24 00:18:19] [INFO] return self._call_impl(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
[2025-07-24 00:18:19] [INFO] return forward_call(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 464, in forward
[2025-07-24 00:18:19] [INFO] query_states = self.q_proj(hidden_states)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
[2025-07-24 00:18:19] [INFO] return self._call_impl(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
[2025-07-24 00:18:19] [INFO] return forward_call(*args, **kwargs)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] File "F:\fluxgym\venv\Lib\site-packages\torch\nn\modules\linear.py", line 125, in forward
[2025-07-24 00:18:19] [INFO] return F.linear(input, self.weight, self.bias)
[2025-07-24 00:18:19] [INFO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-24 00:18:19] [INFO] RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Cdesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`
"""

I dunno first time see this

"RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Cdesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`"

Btw my comfyui with zluda is working really nice i even managed to work with triton which gives like 2 iterations per second with flux dev model. And with out triton i get like 1,8 iterations per second.
Now only the damn lora training must work then. I really need this lora training its all about lora Charackter ID. And because im german i dont trust to put my datasets on the cloud for lora training due GDPR

**Comment by CS1o** [comment]
I have to retest the Fluxgym setup on my end again it seems.
WIll update how it goes.

In the meantime you can install OneTrainer with Zluda. It works with Flux and SDXL too.
OneTrainer Guide will also get an update soon.

**Comment by HarmlessDiva** [comment]
so an update from my side i managed to get it work the flux training inside comfyui locally, but turned out that my first lora is a only a colourfull denoised picture. I dunno why but i guess ive to keep learning in order to get better. Also via amd zluda emulation doesnt make it easier. If any1 has some advice how to fix this:

<img width="512" height="512" alt="Image" src="https://github.com/user-attachments/assets/8bc308dc-f875-4406-8ab4-8e1915a8cb60" />

My setup was like:

- 25 images ala 512x512 with the txt image caption
- batch size 1
- network dim 64
- network alpha 64
- max training steps like 3000
- epoch 4 (750 per epoch)
- pf8 base
- gradient_dtype bf16
- save_dtype bf16

Any suggestion

**Comment by CS1o** [comment]
Can't help with comfyui and lora training and i also wouldn't recommend using comfyui for training.
It seems like Khoya_ss can work as reported here: https://github.com/CS1o/Stable-Diffusion-Info/issues/47#issuecomment-3189619027

**Comment by HarmlessDiva** [comment]
i wonder if some1 managed anyway to run training on amd windows setup. I think its possible on linux. Feels bad but lets see how AMD develops the AI on their consumer GPU or in general. I may get two used rtx 3090 for a local AI workstation. Maybe best solution. As right now used rtx 3090 is the best budget you can get for your money.
