### ISSUE TITLE
rocBLAS error: Cannot read %HIP_PATH%bin\rocblas/library\TensileLibrary.dat

### ISSUE THREAD

**Issue by svm-zhang** [CS1o/Stable-Diffusion-Info#6]
Hello,

Thanks for the detailed guide.

## My setup

- AMD 6800XT
- AMD driver: 24.9.1
- AMD HIP SDK: 6.1.2 (Install without Pro)
- ZLUDA: windows-rocm6-amd64.zip
- PATH sys env variable set as in the guide

I have followed the step-by-step wiki guide on how to run AUTOMATIC111 with ZLUDA.

Below is the error I got:

```
rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\6.1\bin\/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1036

rocBLAS error: Could not initialize Tensile host:
regex_error(error_backref): The expression contained an invalid back reference.
```

The HIP SDK installation folder, where rocBLAS complains, indeed does not have the `TensileLIbrary.dat` file. It makes me think the HIP SDK installation had problems. Do I need to go down to version 5.7?

I did see a couple of other tickets reporting the same error. But I did not see any of them was fixed.

I could give you more info if needed. Thanks in advance for any help.

**Comment by CS1o** [comment]
Hey, this is a hip bug as it found your CPUs iGPU (gfx1036) before your dedicated GPU.

To fix this you have to open up the Device Manager and under Display Adapters disable the Radeon TM Graphics.

Or you can add: HIP_VISIBLE_DEVICES=1
to the webui-user.bat

Then relaunch the webui-user.bat

**Comment by svm-zhang** [comment]
Thank you very much. Both solutions worked for me.

**Comment by Cappyadams** [comment]
Hey I hope it's okay to ask, but where do I put "HIP_VISIBLE_DEVICES=1"? do I put it in "set GIT=" or where? *sorry for the dumb question*

**Comment by svm-zhang** [comment]
> Hey I hope it's okay to ask, but where do I put "HIP_VISIBLE_DEVICES=1"? do I put it in "set GIT=" or where? _sorry for the dumb question_

I added it to the `webui-user.bat' file as

```
set HIP_VISIBLE_DEVICES=1
```

Hope this helps :)
